In [1]:
import pandas as pd
import numpy as np

In [2]:
array_exemplo = np.array([[2,3,5,7],[11,13,17,19],[23,29,31,37,], [41,43,47,49]])
array_exemplo

array([[ 2,  3,  5,  7],
       [11, 13, 17, 19],
       [23, 29, 31, 37],
       [41, 43, 47, 49]])

In [3]:
array_exemplo[1,1]

np.int64(13)

In [4]:
array_exemplo[1,:]

array([11, 13, 17, 19])

In [5]:
array_exemplo[:,1]

array([ 3, 13, 29, 43])

In [6]:
array_exemplo

array([[ 2,  3,  5,  7],
       [11, 13, 17, 19],
       [23, 29, 31, 37],
       [41, 43, 47, 49]])

In [7]:
array_exemplo[1:3,:]

array([[11, 13, 17, 19],
       [23, 29, 31, 37]])

In [8]:
array_exemplo[1:3,0:2]

array([[11, 13],
       [23, 29]])

In [9]:
array_exemplo[1:3,[0,2]]

array([[11, 17],
       [23, 31]])

In [10]:
# observar que salvei o arquivo da base de dados no meu diretório
# verificar o de vocês
#
base_adulto = pd.read_csv('./adulto.csv')

In [11]:
base_adulto.loc[:,'education':'occupation']

        education  education-num      marital-status         occupation
0       Bachelors             13       Never-married       Adm-clerical
1       Bachelors             13  Married-civ-spouse    Exec-managerial
2         HS-grad              9            Divorced  Handlers-cleaners
3            11th              7  Married-civ-spouse  Handlers-cleaners
4       Bachelors             13  Married-civ-spouse     Prof-specialty
...           ...            ...                 ...                ...
32556  Assoc-acdm             12  Married-civ-spouse       Tech-support
32557     HS-grad              9  Married-civ-spouse  Machine-op-inspct
32558     HS-grad              9             Widowed       Adm-clerical
32559     HS-grad              9       Never-married       Adm-clerical
32560     HS-grad              9  Married-civ-spouse    Exec-managerial

[32561 rows x 4 columns]

In [12]:
base_adulto.sort_values('education-num').reset_index().iloc[1:32561:3617]

,index,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalGain,capitalLoss,hoursPerWeek,nativeCountry,income
1,32224,40,Private,70645,Preschool,1,Never-married,Other-service,Not-in-family,White,Female,0,0,20,United-States,<=50K
3618,25200,38,Private,171344,11th,7,Married-spouse-absent,Transport-moving,Own-child,White,Male,0,0,36,Mexico,<=50K
7235,7259,30,Private,231263,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,<=50K
10852,20281,33,Private,214635,HS-grad,9,Married-civ-spouse,Other-service,Husband,Black,Male,0,0,36,Haiti,<=50K
14469,15145,34,Private,318886,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
18086,3102,22,Private,221745,Some-college,10,Divorced,Machine-op-inspct,Own-child,White,Female,0,0,40,United-States,<=50K
21703,9845,23,Private,45317,Some-college,10,Separated,Sales,Own-child,White,Female,0,0,40,United-States,<=50K
25320,9055,74,Private,180455,Bachelors,13,Widowed,Other-service,Not-in-family,White,Female,0,0,8,United-States,<=50K
28937,16446,50,Self-emp-not-inc,186565,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
32554,4438,68,Private,128472,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,55,United-States,>50K