In [7]:
# baixar inicialmente do MCOnf da disciplina a base de dados
# chamada de 'adultos.csv"
# salvar a mesma em diretório a sua escolha
# observar o endereço do diretório ao "ler" esta base de dados

In [8]:
import pandas as pd
import numpy as np

In [9]:
base_adulto = pd.read_csv('./adulto.csv')

In [10]:
base_adulto.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalGain,capitalLoss,hoursPerWeek,nativeCountry,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [11]:
type(base_adulto.age)

pandas.Series

In [12]:
type(base_adulto)

pandas.DataFrame

In [13]:
base_adulto.loc[0].index

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capitalGain', 'capitalLoss', 'hoursPerWeek', 'nativeCountry',
       'income'],
      dtype='str')

In [14]:
base_adulto.age.index

RangeIndex(start=0, stop=32561, step=1)

In [15]:
base_adulto.workclass.index

RangeIndex(start=0, stop=32561, step=1)

In [16]:
len(base_adulto)

32561

In [17]:
base_adulto.set_index(np.arange(10000,42561),inplace=True)

In [18]:
base_adulto.set_index(np.arange(10000,42561))

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalGain,capitalLoss,hoursPerWeek,nativeCountry,income
10000,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
10001,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
10002,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
10003,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
10004,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
42557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
42558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
42559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
42560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [19]:
base_adulto.loc[10001]

age                               50
workclass           Self-emp-not-inc
fnlwgt                         83311
education                  Bachelors
education-num                     13
marital-status    Married-civ-spouse
occupation           Exec-managerial
relationship                 Husband
race                           White
sex                             Male
capitalGain                        0
capitalLoss                        0
hoursPerWeek                      13
nativeCountry          United-States
income                         <=50K
Name: 10001, dtype: object

In [20]:
base_adulto.iloc[1]

age                               50
workclass           Self-emp-not-inc
fnlwgt                         83311
education                  Bachelors
education-num                     13
marital-status    Married-civ-spouse
occupation           Exec-managerial
relationship                 Husband
race                           White
sex                             Male
capitalGain                        0
capitalLoss                        0
hoursPerWeek                      13
nativeCountry          United-States
income                         <=50K
Name: 10001, dtype: object

In [21]:
base_adulto.age

10000    39
10001    50
10002    38
10003    53
10004    28
         ..
42556    27
42557    40
42558    58
42559    22
42560    52
Name: age, Length: 32561, dtype: int64

In [22]:
base_adulto.occupation

10000         Adm-clerical
10001      Exec-managerial
10002    Handlers-cleaners
10003    Handlers-cleaners
10004       Prof-specialty
               ...
42556         Tech-support
42557    Machine-op-inspct
42558         Adm-clerical
42559         Adm-clerical
42560      Exec-managerial
Name: occupation, Length: 32561, dtype: str

In [23]:
base_adulto['age']

10000    39
10001    50
10002    38
10003    53
10004    28
         ..
42556    27
42557    40
42558    58
42559    22
42560    52
Name: age, Length: 32561, dtype: int64

In [24]:
base_adulto.iloc[2].loc['education']

'HS-grad'

In [25]:
base_adulto.education.loc[10002]

'HS-grad'

In [26]:
base_adulto['education'].iloc[2]

'HS-grad'

In [27]:
base_adulto.at[10002,'education']

'HS-grad'